package com.mobitest.model;
// Generated 2013-8-3 23:53:43 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tt generated by hbm2java
 */
@Entity
@Table(name="tt"
    ,catalog="taxm"
)
public class Tt  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date upateDate;

    public Tt() {
    }

    public Tt(String name, Date upateDate) {
       this.name = name;
       this.upateDate = upateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="upate_date", nullable=false, length=19)
    public Date getUpateDate() {
        return this.upateDate;
    }
    
    public void setUpateDate(Date upateDate) {
        this.upateDate = upateDate;
    }




}


