package mt.taxm.model;
// Generated 2013-8-27 13:07:45 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * AppVersion generated by hbm2java
 */
@Entity
@Table(name="APP_VERSION"
)

@NamedQueries({
	@NamedQuery(
	name = "lastVersion",
	query = "select s FROM AppVersion s where s.id=(select max(a.id) from AppVersion a)"
	)
})
public class AppVersion  implements java.io.Serializable {


     private Long id;
     private Long num;
     private String title;
     private String releaseNotes;
     private String remark;
     private Date releaseDate;
     private String url;
     private Long mustUpdate;

    public AppVersion() {
    }

	
    public AppVersion(Long id, Long num) {
        this.id = id;
        this.num = num;
    }
    public AppVersion(Long id, Long num, String title, String releaseNotes, String remark, Date releaseDate, String url, Long mustUpdate) {
       this.id = id;
       this.num = num;
       this.title = title;
       this.releaseNotes = releaseNotes;
       this.remark = remark;
       this.releaseDate = releaseDate;
       this.url = url;
       this.mustUpdate = mustUpdate;
    }
   
     @Id 
     @GeneratedValue(generator = "appversionGen")    
     @GenericGenerator(name = "appversionGen", strategy = "increment")  
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="NUM", nullable=false, precision=22, scale=0)
    public Long getNum() {
        return this.num;
    }
    
    public void setNum(Long num) {
        this.num = num;
    }
    
    @Column(name="TITLE", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="RELEASE_NOTES", length=800)
    public String getReleaseNotes() {
        return this.releaseNotes;
    }
    
    public void setReleaseNotes(String releaseNotes) {
        this.releaseNotes = releaseNotes;
    }
    
    @Column(name="REMARK", length=400)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RELEASE_DATE", length=7)
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    
    @Column(name="URL", length=200)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="MUST_UPDATE", precision=22, scale=0)
    public Long getMustUpdate() {
        return this.mustUpdate;
    }
    
    public void setMustUpdate(Long mustUpdate) {
        this.mustUpdate = mustUpdate;
    }




}


