package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TNsrsbqkId generated by hbm2java
 */
@Embeddable
public class TNsrsbqkId  implements java.io.Serializable {


     private long nsrnbm;
     private String zsxm;
     private Date sfssqQsrq;
     private Date sfssqZzrq;

    public TNsrsbqkId() {
    }

    public TNsrsbqkId(long nsrnbm, String zsxm, Date sfssqQsrq, Date sfssqZzrq) {
       this.nsrnbm = nsrnbm;
       this.zsxm = zsxm;
       this.sfssqQsrq = sfssqQsrq;
       this.sfssqZzrq = sfssqZzrq;
    }
   

    @Column(name="NSRNBM", nullable=false, precision=10, scale=0)
    public long getNsrnbm() {
        return this.nsrnbm;
    }
    
    public void setNsrnbm(long nsrnbm) {
        this.nsrnbm = nsrnbm;
    }

    @Column(name="ZSXM", nullable=false, length=100)
    public String getZsxm() {
        return this.zsxm;
    }
    
    public void setZsxm(String zsxm) {
        this.zsxm = zsxm;
    }

    @Column(name="SFSSQ_QSRQ", nullable=false, length=7)
    public Date getSfssqQsrq() {
        return this.sfssqQsrq;
    }
    
    public void setSfssqQsrq(Date sfssqQsrq) {
        this.sfssqQsrq = sfssqQsrq;
    }

    @Column(name="SFSSQ_ZZRQ", nullable=false, length=7)
    public Date getSfssqZzrq() {
        return this.sfssqZzrq;
    }
    
    public void setSfssqZzrq(Date sfssqZzrq) {
        this.sfssqZzrq = sfssqZzrq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TNsrsbqkId) ) return false;
		 TNsrsbqkId castOther = ( TNsrsbqkId ) other; 
         
		 return (this.getNsrnbm()==castOther.getNsrnbm())
 && ( (this.getZsxm()==castOther.getZsxm()) || ( this.getZsxm()!=null && castOther.getZsxm()!=null && this.getZsxm().equals(castOther.getZsxm()) ) )
 && ( (this.getSfssqQsrq()==castOther.getSfssqQsrq()) || ( this.getSfssqQsrq()!=null && castOther.getSfssqQsrq()!=null && this.getSfssqQsrq().equals(castOther.getSfssqQsrq()) ) )
 && ( (this.getSfssqZzrq()==castOther.getSfssqZzrq()) || ( this.getSfssqZzrq()!=null && castOther.getSfssqZzrq()!=null && this.getSfssqZzrq().equals(castOther.getSfssqZzrq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNsrnbm();
         result = 37 * result + ( getZsxm() == null ? 0 : this.getZsxm().hashCode() );
         result = 37 * result + ( getSfssqQsrq() == null ? 0 : this.getSfssqQsrq().hashCode() );
         result = 37 * result + ( getSfssqZzrq() == null ? 0 : this.getSfssqZzrq().hashCode() );
         return result;
   }   


}


