package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TNsrhdqkId generated by hbm2java
 */
@Embeddable
public class TNsrhdqkId  implements java.io.Serializable {


     private long nsrnbm;
     private String sz;
     private String pm;
     private Date hdQsrq;

    public TNsrhdqkId() {
    }

    public TNsrhdqkId(long nsrnbm, String sz, String pm, Date hdQsrq) {
       this.nsrnbm = nsrnbm;
       this.sz = sz;
       this.pm = pm;
       this.hdQsrq = hdQsrq;
    }
   

    @Column(name="NSRNBM", nullable=false, precision=10, scale=0)
    public long getNsrnbm() {
        return this.nsrnbm;
    }
    
    public void setNsrnbm(long nsrnbm) {
        this.nsrnbm = nsrnbm;
    }

    @Column(name="SZ", nullable=false, length=100)
    public String getSz() {
        return this.sz;
    }
    
    public void setSz(String sz) {
        this.sz = sz;
    }

    @Column(name="PM", nullable=false, length=100)
    public String getPm() {
        return this.pm;
    }
    
    public void setPm(String pm) {
        this.pm = pm;
    }

    @Column(name="HD_QSRQ", nullable=false, length=7)
    public Date getHdQsrq() {
        return this.hdQsrq;
    }
    
    public void setHdQsrq(Date hdQsrq) {
        this.hdQsrq = hdQsrq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TNsrhdqkId) ) return false;
		 TNsrhdqkId castOther = ( TNsrhdqkId ) other; 
         
		 return (this.getNsrnbm()==castOther.getNsrnbm())
 && ( (this.getSz()==castOther.getSz()) || ( this.getSz()!=null && castOther.getSz()!=null && this.getSz().equals(castOther.getSz()) ) )
 && ( (this.getPm()==castOther.getPm()) || ( this.getPm()!=null && castOther.getPm()!=null && this.getPm().equals(castOther.getPm()) ) )
 && ( (this.getHdQsrq()==castOther.getHdQsrq()) || ( this.getHdQsrq()!=null && castOther.getHdQsrq()!=null && this.getHdQsrq().equals(castOther.getHdQsrq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNsrnbm();
         result = 37 * result + ( getSz() == null ? 0 : this.getSz().hashCode() );
         result = 37 * result + ( getPm() == null ? 0 : this.getPm().hashCode() );
         result = 37 * result + ( getHdQsrq() == null ? 0 : this.getHdQsrq().hashCode() );
         return result;
   }   


}


