package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * TNsrhdqk generated by hbm2java
 */
@Entity
@Table(name="T_NSRHDQK"
)
@NamedQueries({
	@NamedQuery(
	name = "hdByBm",
	query = "select s FROM TNsrhdqk s where s.nsrbm like :bm order by s.hdZzrq desc"
	)
})

public class TNsrhdqk  implements java.io.Serializable {


     private TNsrhdqkId id;
     private String nsrbm;
     private BigDecimal jsje;
     private BigDecimal sl;
     private BigDecimal sskcs;
     private BigDecimal ynse;
     private String zsfs;
     private String nsqx;
     private String sbqx;
     private String jsyj;
     private String jkmc;
     private Date hdZzrq;

    public TNsrhdqk() {
    }

	
    public TNsrhdqk(TNsrhdqkId id, String nsrbm) {
        this.id = id;
        this.nsrbm = nsrbm;
    }
    public TNsrhdqk(TNsrhdqkId id, String nsrbm, BigDecimal jsje, BigDecimal sl, BigDecimal sskcs, BigDecimal ynse, String zsfs, String nsqx, String sbqx, String jsyj, String jkmc, Date hdZzrq) {
       this.id = id;
       this.nsrbm = nsrbm;
       this.jsje = jsje;
       this.sl = sl;
       this.sskcs = sskcs;
       this.ynse = ynse;
       this.zsfs = zsfs;
       this.nsqx = nsqx;
       this.sbqx = sbqx;
       this.jsyj = jsyj;
       this.jkmc = jkmc;
       this.hdZzrq = hdZzrq;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="nsrnbm", column=@Column(name="NSRNBM", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="sz", column=@Column(name="SZ", nullable=false, length=100) ), 
        @AttributeOverride(name="pm", column=@Column(name="PM", nullable=false, length=100) ), 
        @AttributeOverride(name="hdQsrq", column=@Column(name="HD_QSRQ", nullable=false, length=7) ) } )
    public TNsrhdqkId getId() {
        return this.id;
    }
    
    public void setId(TNsrhdqkId id) {
        this.id = id;
    }
    
    @Column(name="NSRBM", nullable=false, length=20)
    public String getNsrbm() {
        return this.nsrbm;
    }
    
    public void setNsrbm(String nsrbm) {
        this.nsrbm = nsrbm;
    }
    
    @Column(name="JSJE", precision=18)
    public BigDecimal getJsje() {
        return this.jsje;
    }
    
    public void setJsje(BigDecimal jsje) {
        this.jsje = jsje;
    }
    
    @Column(name="SL", precision=16, scale=6)
    public BigDecimal getSl() {
        return this.sl;
    }
    
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }
    
    @Column(name="SSKCS", precision=16, scale=6)
    public BigDecimal getSskcs() {
        return this.sskcs;
    }
    
    public void setSskcs(BigDecimal sskcs) {
        this.sskcs = sskcs;
    }
    
    @Column(name="YNSE", precision=18)
    public BigDecimal getYnse() {
        return this.ynse;
    }
    
    public void setYnse(BigDecimal ynse) {
        this.ynse = ynse;
    }
    
    @Column(name="ZSFS", length=100)
    public String getZsfs() {
        return this.zsfs;
    }
    
    public void setZsfs(String zsfs) {
        this.zsfs = zsfs;
    }
    
    @Column(name="NSQX", length=100)
    public String getNsqx() {
        return this.nsqx;
    }
    
    public void setNsqx(String nsqx) {
        this.nsqx = nsqx;
    }
    
    @Column(name="SBQX", length=100)
    public String getSbqx() {
        return this.sbqx;
    }
    
    public void setSbqx(String sbqx) {
        this.sbqx = sbqx;
    }
    
    @Column(name="JSYJ", length=100)
    public String getJsyj() {
        return this.jsyj;
    }
    
    public void setJsyj(String jsyj) {
        this.jsyj = jsyj;
    }
    
    @Column(name="JKMC", length=100)
    public String getJkmc() {
        return this.jkmc;
    }
    
    public void setJkmc(String jkmc) {
        this.jkmc = jkmc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HD_ZZRQ", length=7)
    public Date getHdZzrq() {
        return this.hdZzrq;
    }
    
    public void setHdZzrq(Date hdZzrq) {
        this.hdZzrq = hdZzrq;
    }




}


