package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TNsrnsqkId generated by hbm2java
 */
@Embeddable
public class TNsrnsqkId  implements java.io.Serializable {


     private long nsrnbm;
     private String nsrbm;
     private String sz;
     private Date sfssqQsrq;
     private Date sfssqZzrq;
     private String jkQx;
     private BigDecimal yzsfJe;

    public TNsrnsqkId() {
    }

	
    public TNsrnsqkId(long nsrnbm, String nsrbm) {
        this.nsrnbm = nsrnbm;
        this.nsrbm = nsrbm;
    }
    public TNsrnsqkId(long nsrnbm, String nsrbm, String sz, Date sfssqQsrq, Date sfssqZzrq, String jkQx, BigDecimal yzsfJe) {
       this.nsrnbm = nsrnbm;
       this.nsrbm = nsrbm;
       this.sz = sz;
       this.sfssqQsrq = sfssqQsrq;
       this.sfssqZzrq = sfssqZzrq;
       this.jkQx = jkQx;
       this.yzsfJe = yzsfJe;
    }
   

    @Column(name="NSRNBM", nullable=false, precision=10, scale=0)
    public long getNsrnbm() {
        return this.nsrnbm;
    }
    
    public void setNsrnbm(long nsrnbm) {
        this.nsrnbm = nsrnbm;
    }

    @Column(name="NSRBM", nullable=false, length=20)
    public String getNsrbm() {
        return this.nsrbm;
    }
    
    public void setNsrbm(String nsrbm) {
        this.nsrbm = nsrbm;
    }

    @Column(name="SZ", length=100)
    public String getSz() {
        return this.sz;
    }
    
    public void setSz(String sz) {
        this.sz = sz;
    }

    @Column(name="SFSSQ_QSRQ", length=7)
    public Date getSfssqQsrq() {
        return this.sfssqQsrq;
    }
    
    public void setSfssqQsrq(Date sfssqQsrq) {
        this.sfssqQsrq = sfssqQsrq;
    }

    @Column(name="SFSSQ_ZZRQ", length=7)
    public Date getSfssqZzrq() {
        return this.sfssqZzrq;
    }
    
    public void setSfssqZzrq(Date sfssqZzrq) {
        this.sfssqZzrq = sfssqZzrq;
    }

    @Column(name="JK_QX", length=100)
    public String getJkQx() {
        return this.jkQx;
    }
    
    public void setJkQx(String jkQx) {
        this.jkQx = jkQx;
    }

    @Column(name="YZSF_JE", precision=18)
    public BigDecimal getYzsfJe() {
        return this.yzsfJe;
    }
    
    public void setYzsfJe(BigDecimal yzsfJe) {
        this.yzsfJe = yzsfJe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TNsrnsqkId) ) return false;
		 TNsrnsqkId castOther = ( TNsrnsqkId ) other; 
         
		 return (this.getNsrnbm()==castOther.getNsrnbm())
 && ( (this.getNsrbm()==castOther.getNsrbm()) || ( this.getNsrbm()!=null && castOther.getNsrbm()!=null && this.getNsrbm().equals(castOther.getNsrbm()) ) )
 && ( (this.getSz()==castOther.getSz()) || ( this.getSz()!=null && castOther.getSz()!=null && this.getSz().equals(castOther.getSz()) ) )
 && ( (this.getSfssqQsrq()==castOther.getSfssqQsrq()) || ( this.getSfssqQsrq()!=null && castOther.getSfssqQsrq()!=null && this.getSfssqQsrq().equals(castOther.getSfssqQsrq()) ) )
 && ( (this.getSfssqZzrq()==castOther.getSfssqZzrq()) || ( this.getSfssqZzrq()!=null && castOther.getSfssqZzrq()!=null && this.getSfssqZzrq().equals(castOther.getSfssqZzrq()) ) )
 && ( (this.getJkQx()==castOther.getJkQx()) || ( this.getJkQx()!=null && castOther.getJkQx()!=null && this.getJkQx().equals(castOther.getJkQx()) ) )
 && ( (this.getYzsfJe()==castOther.getYzsfJe()) || ( this.getYzsfJe()!=null && castOther.getYzsfJe()!=null && this.getYzsfJe().equals(castOther.getYzsfJe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNsrnbm();
         result = 37 * result + ( getNsrbm() == null ? 0 : this.getNsrbm().hashCode() );
         result = 37 * result + ( getSz() == null ? 0 : this.getSz().hashCode() );
         result = 37 * result + ( getSfssqQsrq() == null ? 0 : this.getSfssqQsrq().hashCode() );
         result = 37 * result + ( getSfssqZzrq() == null ? 0 : this.getSfssqZzrq().hashCode() );
         result = 37 * result + ( getJkQx() == null ? 0 : this.getJkQx().hashCode() );
         result = 37 * result + ( getYzsfJe() == null ? 0 : this.getYzsfJe().hashCode() );
         return result;
   }   


}


