package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TNsrfpgzqkId generated by hbm2java
 */
@Embeddable
public class TNsrfpgzqkId  implements java.io.Serializable {


     private long nsrnbm;
     private String fpzl;
     private String fpQshm;

    public TNsrfpgzqkId() {
    }

    public TNsrfpgzqkId(long nsrnbm, String fpzl, String fpQshm) {
       this.nsrnbm = nsrnbm;
       this.fpzl = fpzl;
       this.fpQshm = fpQshm;
    }
   

    @Column(name="NSRNBM", nullable=false, precision=10, scale=0)
    public long getNsrnbm() {
        return this.nsrnbm;
    }
    
    public void setNsrnbm(long nsrnbm) {
        this.nsrnbm = nsrnbm;
    }

    @Column(name="FPZL", nullable=false, length=100)
    public String getFpzl() {
        return this.fpzl;
    }
    
    public void setFpzl(String fpzl) {
        this.fpzl = fpzl;
    }

    @Column(name="FP_QSHM", nullable=false, length=10)
    public String getFpQshm() {
        return this.fpQshm;
    }
    
    public void setFpQshm(String fpQshm) {
        this.fpQshm = fpQshm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TNsrfpgzqkId) ) return false;
		 TNsrfpgzqkId castOther = ( TNsrfpgzqkId ) other; 
         
		 return (this.getNsrnbm()==castOther.getNsrnbm())
 && ( (this.getFpzl()==castOther.getFpzl()) || ( this.getFpzl()!=null && castOther.getFpzl()!=null && this.getFpzl().equals(castOther.getFpzl()) ) )
 && ( (this.getFpQshm()==castOther.getFpQshm()) || ( this.getFpQshm()!=null && castOther.getFpQshm()!=null && this.getFpQshm().equals(castOther.getFpQshm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNsrnbm();
         result = 37 * result + ( getFpzl() == null ? 0 : this.getFpzl().hashCode() );
         result = 37 * result + ( getFpQshm() == null ? 0 : this.getFpQshm().hashCode() );
         return result;
   }   


}


