package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * TNsrfpgzqk generated by hbm2java
 */
@Entity
@Table(name="T_NSRFPGZQK"
    ,schema="ZGPAD"
)
@NamedQueries({
	@NamedQuery(
	name = "fpgzByBm",
	query = "select s FROM TNsrfpgzqk s where s.nsrbm like :bm order by s.xsRq"
	)
})
public class TNsrfpgzqk  implements java.io.Serializable {


     private TNsrfpgzqkId id;
     private String nsrbm;
     private String fppc;
     private String fpZzhm;
     private String jldw;
     private Integer sl;
     private Date xsRq;
     private String zt;

    public TNsrfpgzqk() {
    }

	
    public TNsrfpgzqk(TNsrfpgzqkId id, String nsrbm) {
        this.id = id;
        this.nsrbm = nsrbm;
    }
    public TNsrfpgzqk(TNsrfpgzqkId id, String nsrbm, String fppc, String fpZzhm, String jldw, Integer sl, Date xsRq, String zt) {
       this.id = id;
       this.nsrbm = nsrbm;
       this.fppc = fppc;
       this.fpZzhm = fpZzhm;
       this.jldw = jldw;
       this.sl = sl;
       this.xsRq = xsRq;
       this.zt = zt;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="nsrnbm", column=@Column(name="NSRNBM", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="fpzl", column=@Column(name="FPZL", nullable=false, length=100) ), 
        @AttributeOverride(name="fpQshm", column=@Column(name="FP_QSHM", nullable=false, length=10) ) } )
    public TNsrfpgzqkId getId() {
        return this.id;
    }
    
    public void setId(TNsrfpgzqkId id) {
        this.id = id;
    }
    
    @Column(name="NSRBM", nullable=false, length=20)
    public String getNsrbm() {
        return this.nsrbm;
    }
    
    public void setNsrbm(String nsrbm) {
        this.nsrbm = nsrbm;
    }
    
    @Column(name="FPPC", length=100)
    public String getFppc() {
        return this.fppc;
    }
    
    public void setFppc(String fppc) {
        this.fppc = fppc;
    }
    
    @Column(name="FP_ZZHM", length=10)
    public String getFpZzhm() {
        return this.fpZzhm;
    }
    
    public void setFpZzhm(String fpZzhm) {
        this.fpZzhm = fpZzhm;
    }
    
    @Column(name="JLDW", length=60)
    public String getJldw() {
        return this.jldw;
    }
    
    public void setJldw(String jldw) {
        this.jldw = jldw;
    }
    
    @Column(name="SL", precision=8, scale=0)
    public Integer getSl() {
        return this.sl;
    }
    
    public void setSl(Integer sl) {
        this.sl = sl;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="XS_RQ", length=7)
    public Date getXsRq() {
        return this.xsRq;
    }
    
    public void setXsRq(Date xsRq) {
        this.xsRq = xsRq;
    }
    
    @Column(name="ZT", length=10)
    public String getZt() {
        return this.zt;
    }
    
    public void setZt(String zt) {
        this.zt = zt;
    }




}


