package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * TNsrsbqk generated by hbm2java
 */
@Entity
@Table(name="T_NSRSBQK"
)
@NamedQueries({
	@NamedQuery(
	name = "sbByBm",
	query = "select s FROM TNsrsbqk s where s.nsrbm like :bm order by s.id.sfssqQsrq desc"
	)
})

public class TNsrsbqk  implements java.io.Serializable {


     private TNsrsbqkId id;
     private String nsrbm;
     private String sbqk;
     private String sbzt;

    public TNsrsbqk() {
    }

	
    public TNsrsbqk(TNsrsbqkId id, String nsrbm) {
        this.id = id;
        this.nsrbm = nsrbm;
    }
    public TNsrsbqk(TNsrsbqkId id, String nsrbm, String sbqk, String sbzt) {
       this.id = id;
       this.nsrbm = nsrbm;
       this.sbqk = sbqk;
       this.sbzt = sbzt;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="nsrnbm", column=@Column(name="NSRNBM", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="zsxm", column=@Column(name="ZSXM", nullable=false, length=100) ), 
        @AttributeOverride(name="sfssqQsrq", column=@Column(name="SFSSQ_QSRQ", nullable=false, length=7) ), 
        @AttributeOverride(name="sfssqZzrq", column=@Column(name="SFSSQ_ZZRQ", nullable=false, length=7) ) } )
    public TNsrsbqkId getId() {
        return this.id;
    }
    
    public void setId(TNsrsbqkId id) {
        this.id = id;
    }
    
    @Column(name="NSRBM", nullable=false, length=20)
    public String getNsrbm() {
        return this.nsrbm;
    }
    
    public void setNsrbm(String nsrbm) {
        this.nsrbm = nsrbm;
    }
    
    @Column(name="SBQK", length=20)
    public String getSbqk() {
        return this.sbqk;
    }
    
    public void setSbqk(String sbqk) {
        this.sbqk = sbqk;
    }
    
    @Column(name="SBZT", length=20)
    public String getSbzt() {
        return this.sbzt;
    }
    
    public void setSbzt(String sbzt) {
        this.sbzt = sbzt;
    }




}


