package mt.taxm.webapp.model;
// Generated 2013-8-5 20:50:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * TSbfjfqk generated by hbm2java
 */
@Entity
@Table(name="T_SBFJFQK"
    ,schema="ZGPAD"
)
@NamedQueries({
	@NamedQuery(
	name = "sbfjfByBm",
	query = "select s FROM TSbfjfqk s where s.id.nsrbm like :bm order by s.id.ssq desc"
	)
})

public class TSbfjfqk  implements java.io.Serializable {


     private TSbfjfqkId id;

    public TSbfjfqk() {
    }

    public TSbfjfqk(TSbfjfqkId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="nsrbm", column=@Column(name="NSRBM", nullable=false, length=20) ), 
        @AttributeOverride(name="nsrMc", column=@Column(name="NSR_MC", nullable=false, length=200) ), 
        @AttributeOverride(name="gljg", column=@Column(name="GLJG", length=100) ), 
        @AttributeOverride(name="zsxm", column=@Column(name="ZSXM", nullable=false, length=60) ), 
        @AttributeOverride(name="zspm", column=@Column(name="ZSPM", nullable=false, length=60) ), 
        @AttributeOverride(name="sbfs", column=@Column(name="SBFS", length=20) ), 
        @AttributeOverride(name="sksx1", column=@Column(name="SKSX1", length=20) ), 
        @AttributeOverride(name="sksx2", column=@Column(name="SKSX2", length=20) ), 
        @AttributeOverride(name="sfsx", column=@Column(name="SFSX", length=20) ), 
        @AttributeOverride(name="ssq", column=@Column(name="SSQ", length=20) ), 
        @AttributeOverride(name="sum", column=@Column(name="SUM", length=20) ) } )
    public TSbfjfqkId getId() {
        return this.id;
    }
    
    public void setId(TSbfjfqkId id) {
        this.id = id;
    }




}


